DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    image TEXT NOT NULL,
    title TEXT NOT NULL,
    material TEXT NOT NULL,
    description TEXT NOT NULL

);